apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpm-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpm-service
  template:
    metadata:
      labels:
        app: bpm-service
    spec:
      containers:
        - name: bpm-service
          image: europe-west3-docker.pkg.dev/bachelor-2021-333810/signfluent-images/bpm-service:V0.1
          ports:
            - containerPort: 8000
          env:
            - name: "spring.datasource.username"
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: dbUsername
            - name: "spring.datasource.password"
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: dbPassword
            - name: "spring.datasource.url"
              valueFrom:
                configMapKeyRef:
                  name: bpm-config-map
                  key: dbConnectionString
            - name: "jpa.hibernate.ddl-auto"
              valueFrom:
                configMapKeyRef:
                  name: bpm-config-map
                  key: ddl-auto
            - name: "camunda.bpm.database.schema-update"
              valueFrom:
                configMapKeyRef:
                  name: bpm-config-map
                  key: camunda.schema-update
            - name: "camunda.bpm.database.jdbc-batch-processing"
              valueFrom:
                configMapKeyRef:
                  name: bpm-config-map
                  key: camunda.jdbc-batch-processing
            - name: "camunda.bpm.admin-user.id"
              valueFrom:
                configMapKeyRef:
                  name: bpm-config-map
                  key: camunda.admin-name
            - name: "camunda.bpm.admin-user.password"
              valueFrom:
                configMapKeyRef:
                  name: bpm-config-map
                  key: camunda.admin-password
