apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: europe-west3-docker.pkg.dev/bachelor-2021-333810/signfluent-images/webapp:V0.1
          ports:
            - containerPort: 80
          env:
            - name: "BUSINESS_SERVICE_HOST"
              valueFrom:
                configMapKeyRef:
                  name: webapp-config-map
                  key: businessServiceHost