apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpm-service-deployment
  labels:
    app: bpm-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bpm-service
  template:
    metadata:
      labels:
        app: bpm-service
    spec:
      containers:
        - name: bpm-service
          image: europe-west4-docker.pkg.dev/bachelor-2021-324814/bpr-images/signfluent-bpm-service:V0.8
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: gcp-sa-key
