apiVersion: v1
kind: Service
metadata:
  name: bpm-service-svc
spec:
  selector:
    app: bpm-service
  ports:
    - port: 8181
      targetPort: 8181
      name: http
      protocol: TCP
  type: LoadBalancer
