/*
 * TITLE
 * DESCRIPTION
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dk.signfluent.user.service.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dk.signfluent.user.service.model.DeviceEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RegisterDeviceResponse
 */
public class RegisterDeviceResponseTest {
    private final RegisterDeviceResponse model = new RegisterDeviceResponse();

    /**
     * Model tests for RegisterDeviceResponse
     */
    @Test
    public void testRegisterDeviceResponse() {
        // TODO: test RegisterDeviceResponse
    }

    /**
     * Test the property 'deviceEntity'
     */
    @Test
    public void deviceEntityTest() {
        // TODO: test deviceEntity
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

}
