apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpm-service-deployment
  labels:
    app: bpm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpm-service
  template:
    metadata:
      labels:
        app: bpm-service
    spec:
      containers:
        - name: bpm-service
          imagePullPolicy: Never
          image: signfluent/bpm-service:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: gcp-sa-key
