apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpm-service-deployment
  labels:
    app: bpm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpm-service
  template:
    metadata:
      labels:
        app: bpm-service
    spec:
      containers:
        - name: bpm-service
          imagePullPolicy: Never
          image: signfluent_bpm_service:latest
      imagePullSecrets:
        - name: gcp-sa-key
