apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service-deployment
  labels:
    app: document-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
        - name: document-service
          imagePullPolicy: Never
          image: signfluent_document_service:latest
      imagePullSecrets:
        - name: gcp-sa-key
