apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          imagePullPolicy: Never
          image: signfluent/notification-service:latest
          ports:
            - containerPort: 8003
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: gcp-sa-key
