apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      volumes:
        - name: google-cloud-keys
          secret:
            secretName: firebase-sa-account-credentials
      containers:
        - name: notification-service
          imagePullPolicy: Never
          image: signfluent/notification-service:latest
          ports:
            - containerPort: 8003
          volumeMounts:
            - name: google-cloud-keys
              mountPath: /var/secrets/google
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
