version: '3'

# Comment out the service which does not need to be started
services:
  ui:
    container_name: signfluent-web
    build: ../signfluent-web
    image: europe-west3-docker.pkg.dev/bachelor-2021-333810/signfluent-images/webapp:V0.1

  document_service:
    container_name: document-service
    build: ../document-service
    image: europe-west3-docker.pkg.dev/bachelor-2021-333810/signfluent-images/document-service:V0.1

  bpm_service:
    container_name: bpm-service
    build: ../bpm-service
    image: europe-west3-docker.pkg.dev/bachelor-2021-333810/signfluent-images/bpm-service:V0.1

  notification_service:
    container_name: notification-service
    build: ../notification-service
    image: europe-west3-docker.pkg.dev/bachelor-2021-333810/signfluent-images/notification-service:V0.1

  user_service:
    container_name: user-service
    build: ../user-service
    image: europe-west3-docker.pkg.dev/bachelor-2021-333810/signfluent-images/user-service:V0.1

  certificate_authority:
    container_name: certificate-authority
    build: ../certificate-authority
    image: europe-west3-docker.pkg.dev/bachelor-2021-333810/signfluent-images/certificate-authority:V0.1

  device_service:
    container_name: device-service
    build: ../device-service
    image: europe-west3-docker.pkg.dev/bachelor-2021-333810/signfluent-images/device-service:V0.1

  business_service:
    container_name: business-service
    build: ../business-service
    image: europe-west3-docker.pkg.dev/bachelor-2021-333810/signfluent-images/business-service:V0.1