apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service-deployment
  labels:
    app: device-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-service
  template:
    metadata:
      labels:
        app: device-service
    spec:
      containers:
        - name: device-service
          imagePullPolicy: Never
          image: signfluent/device-service:latest
          ports:
            - containerPort: 8005
          env:
            - name: "spring.datasource.url"
              valueFrom:
                configMapKeyRef:
                  name: device-service-config-map
                  key: dbConnectionString
            - name: "jpa.hibernate.ddl-auto"
              valueFrom:
                configMapKeyRef:
                  name: device-service-config-map
                  key: ddl-auto
            - name: "spring.datasource.username"
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: dbUsername
            - name: "spring.datasource.password"
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: dbPassword
      imagePullSecrets:
        - name: gcp-sa-key
