spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: proof
  password: proof

server:
  port: 8181

bpm:
  service:
    svc:
      service:
        host: localhost
        port: 8181
