keycloak:
  realm: master
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: user-service
  use-resource-role-mappings: true
  public-client: true

idp-keycloak:
  service:
    host: localhost
    port: 8080

camunda.bpm.admin-user:
  id: proof
  password: proof

server:
  port: 8000

document:
  service:
    svc:
      service:
        host: localhost
        port: 8001

user:
  service:
    svc:
      service:
        host: localhost
        port: 8003

device:
  service:
    svc:
      service:
        host: localhost
        port: 8003
