keycloak:
  realm: master
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: signfluent
  use-resource-role-mappings: true
  public-client: true

camunda:
  bpm:
    database:
      schema-update: true
      jdbc-batch-processing: false
    admin-user:
      id: proof
      password: proof

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bpm-service?createDatabaseIfNotExist=true
    username: root
    password: Pa55w0rd
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8000

idp-keycloak:
  service:
    host: localhost
    port: 8080

document:
  service:
    svc:
      service:
        host: localhost
        port: 8001

user:
  service:
    svc:
      service:
        host: localhost
        port: 8003

ca:
  svc:
    service:
      host: localhost
      port: 8004


device:
  service:
    svc:
      service:
        host: localhost
        port: 8005
