
camunda.bpm.admin-user:
  id: proof
  password: proof

server:
  port: 8000

document:
  service:
    svc:
      service:
        host: localhost
        port: 8001

user:
  service:
    svc:
      service:
        host: localhost
        port: 8003

device:
  service:
    svc:
      service:
        host: localhost
        port: 8003
