kind: PersistentVolume
apiVersion: v1
metadata:
  name: document-service-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/keycloak"