server:
  port: 8001

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/document-service?createDatabaseIfNotExist=true
    username: root
    password: Pa55w0rd
  jpa:
    hibernate:
      ddl-auto: create
