/*
 * TITLE
 * DESCRIPTION
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dk.signfluent.user.service.api;

import dk.signfluent.user.service.model.RegisterDeviceRequest;
import dk.signfluent.user.service.model.RegisterDeviceResponse;
import dk.signfluent.user.service.model.UpdateFCMTokenRequest;
import dk.signfluent.user.service.model.UpdateFCMTokenResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeviceControllerApi
 */
@Ignore
public class DeviceControllerApiTest {

    private final DeviceControllerApi api = new DeviceControllerApi();

    
    /**
     * Register Device
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerDeviceTest() {
        RegisterDeviceRequest registerDeviceRequest = null;
        RegisterDeviceResponse response = api.registerDevice(registerDeviceRequest);

        // TODO: test validations
    }
    
    /**
     * Update FCM Token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFCMTokenTest() {
        UpdateFCMTokenRequest updateFCMTokenRequest = null;
        UpdateFCMTokenResponse response = api.updateFCMToken(updateFCMTokenRequest);

        // TODO: test validations
    }
    
}
