/*
 * TITLE
 * DESCRIPTION
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dk.signfluent.user.service.api;

import dk.signfluent.user.service.model.AuthenticationRequest;
import dk.signfluent.user.service.model.AuthenticationResponse;
import dk.signfluent.user.service.model.Device;
import dk.signfluent.user.service.model.User;
import dk.signfluent.user.service.model.UserBasedRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserControllerApi
 */
@Ignore
public class UserControllerApiTest {

    private final UserControllerApi api = new UserControllerApi();

    
    /**
     * Authenticate User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authenticateTest() {
        AuthenticationRequest authenticationRequest = null;
        AuthenticationResponse response = api.authenticate(authenticationRequest);

        // TODO: test validations
    }
    
    /**
     * Get Available Approvers
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAvailableApproversTest() {
        List<User> response = api.getAvailableApprovers();

        // TODO: test validations
    }
    
    /**
     * Get Devices For User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDevicesForUserTest() {
        UserBasedRequest userBasedRequest = null;
        List<Device> response = api.getDevicesForUser(userBasedRequest);

        // TODO: test validations
    }
    
    /**
     * Update FCM Token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFCMTokensForUserTest() {
        UserBasedRequest userBasedRequest = null;
        List<String> response = api.getFCMTokensForUser(userBasedRequest);

        // TODO: test validations
    }
    
}
