/*
 * TITLE
 * DESCRIPTION
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dk.signfluent.user.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * UpdateFCMTokenRequest
 */
@JsonPropertyOrder({
  UpdateFCMTokenRequest.JSON_PROPERTY_DEVICE_ID,
  UpdateFCMTokenRequest.JSON_PROPERTY_FCM_TOKEN,
  UpdateFCMTokenRequest.JSON_PROPERTY_USER_ID
})
@JsonTypeName("UpdateFCMTokenRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-14T14:41:50.888430+02:00[Europe/Copenhagen]")
public class UpdateFCMTokenRequest {
  public static final String JSON_PROPERTY_DEVICE_ID = "deviceId";
  private String deviceId;

  public static final String JSON_PROPERTY_FCM_TOKEN = "fcmToken";
  private String fcmToken;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  private UUID userId;


  public UpdateFCMTokenRequest deviceId(String deviceId) {
    
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeviceId() {
    return deviceId;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }


  public UpdateFCMTokenRequest fcmToken(String fcmToken) {
    
    this.fcmToken = fcmToken;
    return this;
  }

   /**
   * Get fcmToken
   * @return fcmToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FCM_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFcmToken() {
    return fcmToken;
  }


  @JsonProperty(JSON_PROPERTY_FCM_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFcmToken(String fcmToken) {
    this.fcmToken = fcmToken;
  }


  public UpdateFCMTokenRequest userId(UUID userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(UUID userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateFCMTokenRequest updateFCMTokenRequest = (UpdateFCMTokenRequest) o;
    return Objects.equals(this.deviceId, updateFCMTokenRequest.deviceId) &&
        Objects.equals(this.fcmToken, updateFCMTokenRequest.fcmToken) &&
        Objects.equals(this.userId, updateFCMTokenRequest.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, fcmToken, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateFCMTokenRequest {\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    fcmToken: ").append(toIndentedString(fcmToken)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

