apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service-deployment
  labels:
    app: document-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
        - name: document-service
          image: europe-west4-docker.pkg.dev/bachelor-2021-324814/bpr-images/signfluent-document-service:V0.13
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: gcp-sa-key
