apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-deployment
  labels:
    app: ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca
  template:
    metadata:
      labels:
        app: ca
    spec:
      containers:
        - name: ca
          imagePullPolicy: Never
          image: signfluent/certificate-authority:latest
          ports:
            - containerPort: 8004
          env:
            - name: "certificate.keystore.type"
              valueFrom:
                configMapKeyRef:
                  name: ca-config-map
                  key: keystore.type
            - name: "certificate.keystore.password"
              valueFrom:
                configMapKeyRef:
                  name: ca-config-map
                  key: keystore.password
            - name: "certificate.pem"
              valueFrom:
                configMapKeyRef:
                  name: ca-config-map
                  key: p12pem
      imagePullSecrets:
        - name: gcp-sa-key
