apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service-deployment
  labels:
    app: document-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
        - name: document-service
          imagePullPolicy: Never
          image: signfluent/document-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: "spring.datasource.url"
              valueFrom:
                configMapKeyRef:
                  name: document-service-config-map
                  key: dbConnectionString
            - name: "spring.datasource.username"
              valueFrom:
                configMapKeyRef:
                  name: document-service-config-map
                  key: dbUsername
            - name: "spring.datasource.password"
              valueFrom:
                configMapKeyRef:
                  name: document-service-config-map
                  key: dbPassword
            - name: "jpa.hibernate.ddl-auto"
              valueFrom:
                configMapKeyRef:
                  name: document-service-config-map
                  key: ddl-auto
      imagePullSecrets:
        - name: gcp-sa-key
