server:
  port: 8005

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/device-service?createDatabaseIfNotExist=true
    username: root
    password: Pa55w0rd
  jpa:
    hibernate:
      ddl-auto: create